#!/bin/sh
# Skycaptain: Daggerverse
#
# SPDX-License-Identifier: BSD-3-Clause
#
#MISE description="Run tests on all modules"
#
find "${MISE_PROJECT_ROOT}" -name "dagger.json" \
    ! -path "*/sdk/runtime/*" \
    ! -path "*/.renovate/*" \
    ! -path "*/tests/*" \
    -exec sh -c 'dagger call -m "$(dirname "$1")/tests" all' _ {} \;
