# Skycaptain: Daggerverse
#
# SPDX-License-Identifier: BSD-3-Clause
#
name: ci
on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  test-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - kas
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Dagger
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e # 8.0.0
        with:
          # TODO: Add renovate configuration to update this version
          version: "v0.18.10"
          module: "${{ matrix.module }}/tests"
          args: "all"
