# Skycaptain: Daggerverse
#
# SPDX-License-Identifier: BSD-3-Clause
#
name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - kas
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Dagger
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e # 8.0.0
        with:
          # TODO: Add renovate configuration to update this version
          version: "v0.18.10"
          module: "${{ matrix.module }}/tests"
          args: "all"
