# Skycaptain: Daggerverse
#
# SPDX-License-Identifier: BSD-3-Clause
#
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
